# Naraku Game Input Configuration

[KeyboardMouse]
KBM_0=87 # 上移動
KBM_1=83 # 下移動
KBM_2=65 # 左移動
KBM_3=68 # 右移動
KBM_4=257 # 攻撃
KBM_5=70 # 調べる / 利用
KBM_6=32 # ジャンプ
KBM_7=16 # ダッシュ / ステップ
KBM_8=81 # 精神力スキル
KBM_9=69 # 地図を開く
KBM_10=73 # 所持品を開く
KBM_11=27 # 設定 / メニュー
KBM_12=0 # カメラ拡縮ホールド

[XInput]
XIN_0=1 # 上移動
XIN_1=2 # 下移動
XIN_2=4 # 左移動
XIN_3=8 # 右移動
XIN_4=512 # 攻撃
XIN_5=16384 # 調べる / 利用
XIN_6=4096 # ジャンプ
XIN_7=8192 # ダッシュ / ステップ
XIN_8=4097 # 精神力スキル
XIN_9=32768 # 地図を開く
XIN_10=0 # 所持品を開く
XIN_11=16 # 設定 / メニュー
XIN_12=256 # カメラ拡縮ホールド

[DirectInput]
DIN_0=100 # 上移動
DIN_1=102 # 下移動
DIN_2=103 # 左移動
DIN_3=101 # 右移動
DIN_4=5 # 攻撃
DIN_5=2 # 調べる / 利用
DIN_6=0 # ジャンプ
DIN_7=1 # ダッシュ / ステップ
DIN_8=6 # 精神力スキル
DIN_9=3 # 地図を開く
DIN_10=-1 # 所持品を開く
DIN_11=9 # 設定 / メニュー
DIN_12=4 # カメラ拡縮ホールド
DIN_RightStickX=3
DIN_RightStickY=4
DIN_InvertY=1
